# -*- mode: ruby -*-
# vi: set ft=ruby :

class Hash
  def slice(*keep_keys)
    h = {}
    keep_keys.each { |key| h[key] = fetch(key) if has_key?(key) }
    h
  end unless Hash.method_defined?(:slice)
  def except(*less_keys)
    slice(*keys - less_keys)
  end unless Hash.method_defined?(:except)
end

Vagrant.configure("2") do |config|
  config.vm.box = "dummy"

  config.vm.provider :aws do |aws, override|
    
    aws.access_key_id = ENV['VAGRANT_ACCESS_KEY_ID']
    aws.secret_access_key = ENV['VAGRANT_SECRET_ACCESS_KEY']
    aws.keypair_name = "intellipaat-london"

    aws.ami = "ami-04edc9c2bfcf9a772"
    aws.region = "eu-west-2"
    aws.instance_type = "t2.micro"
    aws.security_groups = ['vagrant-sg']
    config.vm.synced_folder ".", "/vagrant", disabled: true
    
    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "/Users/RegiBayoan/Downloads/intellipaat-london.pem"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end

  config.vm.provision "docker" do |d|
    d.build_image "/home/ubuntu/", args: "-t vagrant_image"
    d.run "vagrant_image", image: "vagrant_image", args: "-d -it -p 80:80"
  end
end
